name             'cespi_server_base'
maintainer       'Christian A. Rodriguez & Leandro Di Tommaso'
maintainer_email 'car@cespi.unlp.edu.ar lditommaso@cespi.unlp.edu.ar'
license          'All rights reserved'
description      'Installs/Configures cespi_server_base'
long_description 'Installs/Configures cespi_server_base'
version          '0.1.18'

depends 'apt',          '~>2.6.0'
depends 'ntp',          '~>1.6.4'
depends 'rsyslog',      '~>1.12.2'
depends 'sudo',         '~>2.7.1'
depends 'ubuntu',       '~>1.0.4'
depends 'users',        '~>1.7.0' 
depends 'proxmox-ohai', '~> 0.1.0'
depends 'chef-sugar',   '~> 2.4.1'
